apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - ../mce-base

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
  - target:
      kind: Component
      name: assisted.*
    path: ocm-branch-patch.yaml
  - target:
      kind: Component
      name: hypershift.*
    path: hypershift-branch-patch.yaml