apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - ../mce-base

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
  # - target:
  #     kind: Component
  #     labelSelector: "label=assisted-installer"
  #   path: ocm-branch-path.yaml