apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - ../../../../base # Path to base component

patches:
  - path: component-a-override.yaml # Path to Override File
    target:
      kind: Component