apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: v1 # Add a suffix to all resource names in the application for uniqueness
resources:
  - ../base

patches:
  - target:
      kind: Application
    path: application-patch.yaml
  - target:
      kind: Component
    path: component-patch.yaml
  - target:
      kind: Component
      name: component-b
    path: exception-component-patch-1.yaml
